### ISSUE TITLE
[bug] toYaml does not render output or error

### ISSUE THREAD

**Issue by bluemalkin** [shipmight/helm-playground#2]
Example: https://helm-playground.com/#t=AQ0bzBaYHcEsAuALYA6AagQwDYFcCmAzqgHYD2AJvgMr7b4DGCZATsAL7sBQoo5Vtek1YAuHr3BRgzAJqYAttjTAAPsBJwSVEgmAAODtwnAI0fFsNA&v=HYewJgpgyhA2EGMAuIBOAuAUAAl9sAlgM4DWSAngA4TrZFFg54DmlArrQHIBuBhAhkA

**Comment by codeclown** [comment]
@bluemalkin Thank you for reporting! This has now been fixed. I had accidentally used a different YAML parsing library than Helm uses, which caused an error in unmarshalling, and that error was swallowed in helm_engine.go.
