### ISSUE TITLE
Suggestion: lint output with `yamllint`

### ISSUE THREAD

**Issue by MeurillonGuillaume** [shipmight/helm-playground#7]
Can I start this issue by saying **thank you**. This tool has helped me debug some indentation issues with Helm charts, and for that I'm super grateful.

Now onto the actual issue. When writing `range`s or `if` statements, there are often mistakes in how whitespace controls get used, which might result in poor formatting of the outputted Kubernetes manifest, see [example](https://helm-playground.com/#t=N7C0AIEsDNwUwI7gIwvAX3QKAC5wM47IBc4OAFpPuPuQPYCuANgCbgBGc4TkAdl8iwgIcXm1CZcBHMSzgaDdgBVppClRr1mbTtz5cATEA&v=Q).

Because the chart could be rendered by Helm to a manifest, no errors will be raised before you attempt deploying that manifest. Then Kubernetes will give you an error stating that `mapping values are not allowed in this context at line 2 column 33`.

My suggestion would be to improve the `output` section even further then plain rendering the `template.yaml` + `values.yaml`, and to add a `yaml` linter so that the ouput is validated to be usable or not.

**Comment by codeclown** [comment]
This is a good suggestion. I think the simplest implementation could use the module `sigs.k8s.io/yaml` which is already in go.mod. Just run unmarshal on the output yaml and print out any errors in the UI.

**Comment by codeclown** [comment]
@MeurillonGuillaume thanks for the kind words (glad that the tool has been useful!) and the suggestion. I've added a yellow warning for this use case, you can check it out using your example link.

**Comment by MeurillonGuillaume** [comment]
@codeclown thanks a lot, that's really helpful!
